# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- azure-piplines

pool: 
  name: self-agent

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './build'
    ArtifactName: 'potfolio-art'
    publishLocation: 'Container'
