# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# Set variables once
variables:
  - name: System.Debug
    value: true

trigger:
- azure-piplines

pool: 
  name: self-agent

stages:
  - stage: prep_and_build
    jobs:
    - job: 
      displayName: prepare environment and build
      steps:
      - task: NodeTool@0
        inputs:
          versionSource: 'spec'
          versionSpec: '16.x'
        displayName: 'Install Node.js'

      - script: |
          npm install
        displayName: 'install dependency'
      
      - script: |
          npm run build
        displayName: 'build the project'
        
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: './build'
          ArtifactName: 'potfolio-art'
          publishLocation: 'Container'
    - job: echo_job
      steps:
      - task: CmdLine@2
        inputs:
          script: |
            echo this is just a test
            
            echo Hello world

  - stage: runLast
    displayName: clean the source code
    dependsOn: prep_and_build
    condition: always()
    jobs:
      - job:
        steps:
          - task: DeleteFiles@1
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)'
              Contents: '*'
